name: trigger jenkins job
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: " http://ad9f-93-77-67-224.ngrok.io"
          user: "admin"
          token: ${{ secrets.TOKEN }}
          job: "finalProjectPipeline"